### ISSUE TITLE
Add windows compatibility

### ISSUE THREAD

**Issue by aertist** [tux2603/DeepDream#5]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**System Specs (please complete the following information):**
 - Operating System: [eg, ubuntu, arch]
 - Singularity Version: [eg, 3.6.3]
 - Kernel Version (if applicable): [eg, 5.8.0-2-amd64, 4.15.0-106-generic]
 - GPU: [eg, 1050ti, 2x2080s]
 - GPU driver version: [eg, 440.64]
 - Installed ram and swap space: [eg, 16GB ram, 8GB swap]

**Additional context**

**Comment by tux2603** [comment]
Please fill out the bug template when submitting an issue.

This project does run on windows through WSL2, it just won't have GPU support since Microsoft hasn't fully enabled that yet. All that said, the purpose of this project is to provide a singularity container that handles the installation of all the dependencies automatically, which naturally makes it difficult to provide support for windows. If you are comfortable with installing all the dependencies manually (you can find them in the definition file), you should be able to modify the paths in `src/dream.py` to make it run on windows with GPU. Alternatively, you could check out an alternative deep dream generator such as [google's](https://github.com/google/deepdream/blob/master/dream.ipynb) or [graphific's](https://github.com/graphific/DeepDreamVideo).

I am working on adding built in support for windows through `src/dream.py` using the method I mentioned before, but it is not high on my priorities list right now since

1. It defeats the entire concept of handling dependencies through a singularity container
2. Most people using ML already use Linux or have access to a Linux system
3. There are already a myriad other deep dream generators that will run on windows through this exact same method

**Comment by tux2603** [comment]
`dream.py` can now be run outside of the container with no modifications
